/**
 * Maps every shipped crop id (`data/plants.json`) onto one of the archetypes
 * in `archetypes.ts`. This is the one place a contributor edits to change
 * what shape a crop gets; `generate.ts` fails loudly if a shipped id is
 * missing here (or if an id here no longer exists in the dataset), so this
 * list can never silently drift out of sync with `data/plants.json`.
 *
 * Assignments are a best-effort visual grouping, not botanical taxonomy —
 * several crops in the same family share a shape (all peppers use `pepper`,
 * all onions/garlic use `bulbAllium`) by design, per the brief's steer toward
 * a bounded, consistent placeholder set rather than 160 bespoke illustrations.
 */

import type { ArchetypeKey } from './archetypes.ts';

export const CROP_ARCHETYPES: Record<string, ArchetypeKey> = {
  'acorn-squash': 'squash',
  amaranth: 'leaf',
  'anaheim-pepper': 'pepper',
  apricot: 'roundFruit',
  artichoke: 'flowerHead',
  arugula: 'leaf',
  asparagus: 'stalk',
  'banana-pepper': 'pepper',
  basil: 'herbSprig',
  beet: 'rootRound',
  'bell-pepper': 'pepper',
  'black-currant': 'berryCluster',
  'black-eyed-pea': 'pod',
  blackberry: 'berryCluster',
  blueberry: 'berryCluster',
  'bok-choy': 'leaf',
  borage: 'herbSprig',
  broccoli: 'flowerHead',
  'butternut-squash': 'squash',
  cabbage: 'roundHead',
  cantaloupe: 'melon',
  'cape-gooseberry': 'berryCluster',
  carrot: 'rootLong',
  cauliflower: 'flowerHead',
  'cayenne-pepper': 'pepper',
  celeriac: 'rootRound',
  celery: 'stalk',
  'cherry-tomato': 'roundFruit',
  chervil: 'herbSprig',
  chestnut: 'nut',
  chives: 'herbSprig',
  'choy-sum': 'leaf',
  'collard-greens': 'leaf',
  coriander: 'herbSprig',
  corn: 'corn',
  'cucumber-straight-eight': 'elongatedVeg',
  cumin: 'herbSprig',
  daikon: 'rootLong',
  dandelion: 'leaf',
  'delicata-squash': 'squash',
  dill: 'herbSprig',
  'dragon-fruit': 'dragonFruit',
  eggplant: 'eggplant',
  'elephant-garlic': 'bulbAllium',
  endive: 'leaf',
  feijoa: 'roundFruit',
  fennel: 'herbSprig',
  'french-breakfast-radish': 'rootRound',
  garlic: 'bulbAllium',
  'garlic-chives': 'herbSprig',
  'german-chamomile': 'herbSprig',
  ginger: 'rootRound',
  'golden-beet': 'rootRound',
  gooseberry: 'berryCluster',
  grapefruit: 'roundFruit',
  grapes: 'berryCluster',
  'green-bean': 'pod',
  'green-onion': 'bulbAllium',
  'green-zebra-tomato': 'roundFruit',
  'habanero-pepper': 'pepper',
  'hardy-kiwifruit': 'roundFruit',
  hazelnut: 'nut',
  'heirloom-tomato': 'roundFruit',
  'honeydew-melon': 'melon',
  horseradish: 'rootLong',
  'icicle-radish': 'rootLong',
  'jalapeno-pepper': 'pepper',
  kale: 'leaf',
  kohlrabi: 'rootRound',
  'lacinato-kale': 'leaf',
  'lambs-lettuce': 'leaf',
  leek: 'bulbAllium',
  'lemon-balm': 'herbSprig',
  lemongrass: 'stalk',
  lettuce: 'roundHead',
  licorice: 'herbSprig',
  'looseleaf-lettuce': 'leaf',
  loquat: 'roundFruit',
  lovage: 'herbSprig',
  marjoram: 'herbSprig',
  melon: 'melon',
  'mexican-tarragon': 'herbSprig',
  mint: 'herbSprig',
  mizuna: 'leaf',
  'myoga-ginger': 'rootRound',
  'napa-cabbage': 'roundHead',
  nectarine: 'roundFruit',
  okra: 'okra',
  olive: 'roundFruit',
  onion: 'bulbAllium',
  orange: 'roundFruit',
  papaya: 'roundFruit',
  parsnip: 'rootLong',
  'pattypan-squash': 'squash',
  pawpaw: 'roundFruit',
  pea: 'pod',
  peanut: 'pod',
  persimmon: 'roundFruit',
  pineapple: 'pineapple',
  'pineapple-sage': 'herbSprig',
  plum: 'roundFruit',
  pomegranate: 'roundFruit',
  potato: 'tuber',
  'purple-carrot': 'rootLong',
  'purple-cauliflower': 'flowerHead',
  purslane: 'leaf',
  quince: 'roundFruit',
  radicchio: 'roundHead',
  radish: 'rootRound',
  'rainbow-chard': 'leaf',
  'rainier-cherry': 'berryCluster',
  rapini: 'flowerHead',
  'red-cabbage': 'roundHead',
  'red-currant': 'berryCluster',
  'red-kuri-squash': 'squash',
  'red-onion': 'bulbAllium',
  'red-russian-kale': 'leaf',
  rhubarb: 'stalk',
  'romaine-lettuce': 'leaf',
  romanesco: 'flowerHead',
  rosemary: 'herbSprig',
  'runner-bean': 'pod',
  saffron: 'herbSprig',
  sage: 'herbSprig',
  'salad-burnet': 'herbSprig',
  'sea-kale': 'leaf',
  'serrano-pepper': 'pepper',
  shallot: 'bulbAllium',
  'snap-pea': 'pod',
  'snow-pea': 'pod',
  sorrel: 'leaf',
  soybean: 'pod',
  'spaghetti-squash': 'squash',
  spinach: 'leaf',
  'spring-onion': 'bulbAllium',
  'star-fruit': 'starFruit',
  stevia: 'herbSprig',
  strawberry: 'berryCluster',
  'strawberry-guava': 'roundFruit',
  'summer-savory': 'herbSprig',
  'sweet-potato': 'tuber',
  'swiss-chard-3': 'leaf',
  tarragon: 'herbSprig',
  tatsoi: 'leaf',
  'thai-basil': 'herbSprig',
  thyme: 'herbSprig',
  tomatillo: 'roundFruit',
  tomato: 'roundFruit',
  turnip: 'rootRound',
  'water-spinach': 'leaf',
  watercress: 'leaf',
  'watermelon-radish': 'rootRound',
  'wax-bean': 'pod',
  'white-carrot': 'rootLong',
  'white-currant': 'berryCluster',
  'white-onion': 'bulbAllium',
  'yellow-cauliflower': 'flowerHead',
  'yellow-onion': 'bulbAllium',
  'yellow-strawberry-guava': 'roundFruit',
  zucchini: 'elongatedVeg',
};
