/**
 * Maps every shipped crop id (`data/plants.json`) onto one of the archetypes
 * in `archetypes.ts`. This is the one place a contributor edits to change
 * what shape a crop gets; `generate.ts` fails loudly if a shipped id is
 * missing here (or if an id here no longer exists in the dataset), so this
 * list can never silently drift out of sync with `data/plants.json`.
 *
 * Assignments are a best-effort visual grouping, not botanical taxonomy —
 * several crops in the same family share a shape (all peppers use `pepper`,
 * all onions/garlic use `bulbAllium`) by design, per the brief's steer toward
 * a bounded, consistent placeholder set rather than 160 bespoke illustrations.
 *
 * Stage 6.0 reshaped this list: 24 crops that can't be grown outdoors in
 * Britain left the dataset (`packages/etl/src/exclusions/`, ADR 0025) and six
 * British staples joined it, so this file lost 24 entries and gained six. Five
 * archetypes — `dragonFruit`, `starFruit`, `pineapple`, `okra` and `melon` —
 * now have no crop using them. They are **kept** in `archetypes.ts` rather than
 * deleted: this is a build-time developer tool, so an unused shape costs the
 * shipped app nothing (only the generated icons ship, one per shipped crop),
 * and a fork that wants pineapple back should get its icon by adding one line
 * here, not by redrawing a shape someone already drew.
 */

import type { ArchetypeKey } from './archetypes.ts';

export const CROP_ARCHETYPES: Record<string, ArchetypeKey> = {
  'acorn-squash': 'squash',
  amaranth: 'leaf',
  'anaheim-pepper': 'pepper',
  apple: 'roundFruit',
  apricot: 'roundFruit',
  artichoke: 'flowerHead',
  arugula: 'leaf',
  asparagus: 'stalk',
  'banana-pepper': 'pepper',
  basil: 'herbSprig',
  beet: 'rootRound',
  'bell-pepper': 'pepper',
  'black-currant': 'berryCluster',
  blackberry: 'berryCluster',
  blueberry: 'berryCluster',
  'bok-choy': 'leaf',
  borage: 'herbSprig',
  'broad-bean': 'pod',
  broccoli: 'flowerHead',
  // A sprout is, botanically and visually, a miniature cabbage on a stalk —
  // so it shares `roundHead` with cabbage rather than earning a new shape.
  'brussels-sprouts': 'roundHead',
  'butternut-squash': 'squash',
  cabbage: 'roundHead',
  'cape-gooseberry': 'berryCluster',
  carrot: 'rootLong',
  cauliflower: 'flowerHead',
  'cayenne-pepper': 'pepper',
  celeriac: 'rootRound',
  celery: 'stalk',
  'cherry-tomato': 'roundFruit',
  chervil: 'herbSprig',
  chestnut: 'nut',
  chives: 'herbSprig',
  'choy-sum': 'leaf',
  'collard-greens': 'leaf',
  coriander: 'herbSprig',
  corn: 'corn',
  'cucumber-straight-eight': 'elongatedVeg',
  daikon: 'rootLong',
  dandelion: 'leaf',
  'delicata-squash': 'squash',
  dill: 'herbSprig',
  eggplant: 'eggplant',
  'elephant-garlic': 'bulbAllium',
  endive: 'leaf',
  fennel: 'herbSprig',
  'french-breakfast-radish': 'rootRound',
  garlic: 'bulbAllium',
  'garlic-chives': 'herbSprig',
  'german-chamomile': 'herbSprig',
  'golden-beet': 'rootRound',
  gooseberry: 'berryCluster',
  grapes: 'berryCluster',
  'green-bean': 'pod',
  'green-onion': 'bulbAllium',
  'green-zebra-tomato': 'roundFruit',
  'habanero-pepper': 'pepper',
  'hardy-kiwifruit': 'roundFruit',
  hazelnut: 'nut',
  'heirloom-tomato': 'roundFruit',
  horseradish: 'rootLong',
  'icicle-radish': 'rootLong',
  'jalapeno-pepper': 'pepper',
  'jerusalem-artichoke': 'tuber',
  kale: 'leaf',
  kohlrabi: 'rootRound',
  'lacinato-kale': 'leaf',
  'lambs-lettuce': 'leaf',
  leek: 'bulbAllium',
  'lemon-balm': 'herbSprig',
  lettuce: 'roundHead',
  licorice: 'herbSprig',
  'looseleaf-lettuce': 'leaf',
  lovage: 'herbSprig',
  marjoram: 'herbSprig',
  'mexican-tarragon': 'herbSprig',
  mint: 'herbSprig',
  mizuna: 'leaf',
  'myoga-ginger': 'rootRound',
  'napa-cabbage': 'roundHead',
  nectarine: 'roundFruit',
  onion: 'bulbAllium',
  parsnip: 'rootLong',
  'pattypan-squash': 'squash',
  pea: 'pod',
  pear: 'roundFruit',
  'pineapple-sage': 'herbSprig',
  plum: 'roundFruit',
  potato: 'tuber',
  'purple-carrot': 'rootLong',
  'purple-cauliflower': 'flowerHead',
  purslane: 'leaf',
  pumpkin: 'squash',
  quince: 'roundFruit',
  radicchio: 'roundHead',
  radish: 'rootRound',
  'rainbow-chard': 'leaf',
  'rainier-cherry': 'berryCluster',
  raspberry: 'berryCluster',
  rapini: 'flowerHead',
  'red-cabbage': 'roundHead',
  'red-currant': 'berryCluster',
  'red-kuri-squash': 'squash',
  'red-onion': 'bulbAllium',
  'red-russian-kale': 'leaf',
  rhubarb: 'stalk',
  'romaine-lettuce': 'leaf',
  romanesco: 'flowerHead',
  rosemary: 'herbSprig',
  'runner-bean': 'pod',
  saffron: 'herbSprig',
  sage: 'herbSprig',
  'salad-burnet': 'herbSprig',
  'sea-kale': 'leaf',
  'serrano-pepper': 'pepper',
  shallot: 'bulbAllium',
  'snap-pea': 'pod',
  'snow-pea': 'pod',
  sorrel: 'leaf',
  soybean: 'pod',
  'spaghetti-squash': 'squash',
  spinach: 'leaf',
  'spring-onion': 'bulbAllium',
  stevia: 'herbSprig',
  strawberry: 'berryCluster',
  'summer-savory': 'herbSprig',
  swede: 'rootRound',
  'sweet-potato': 'tuber',
  'swiss-chard-3': 'leaf',
  tarragon: 'herbSprig',
  tatsoi: 'leaf',
  'thai-basil': 'herbSprig',
  thyme: 'herbSprig',
  tomatillo: 'roundFruit',
  tomato: 'roundFruit',
  turnip: 'rootRound',
  watercress: 'leaf',
  'watermelon-radish': 'rootRound',
  'wax-bean': 'pod',
  'white-carrot': 'rootLong',
  'white-currant': 'berryCluster',
  'white-onion': 'bulbAllium',
  'yellow-cauliflower': 'flowerHead',
  'yellow-onion': 'bulbAllium',
  zucchini: 'elongatedVeg',
};
